In [19]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [20]:
dataset = pd.read_csv('hadoop.csv')
X =  pd.DataFrame(dataset, columns = ['ns','nd','nf','entropy','la','ld','lt','fix','ndev','age','nuc','exp','rexp','sexp'])
y = dataset.iloc[:,9:10].values

In [21]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
y = le1.fit_transform(y)
X['fix'] = le2.fit_transform(X['fix'])

/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [37]:
print(X)
print(y)

[[  1.          14.          15.         ...   1.           0.5
    0.        ]
 [  1.           3.           5.         ... 197.           7.63917986
  141.        ]
 [  1.           2.           2.         ...  76.           4.1085649
    8.        ]
 ...
 [  1.           1.           1.         ...  28.          14.20133129
    6.        ]
 [  1.           1.           1.         ...  27.          13.20133129
    5.        ]
 [  0.           0.           0.         ...   0.           0.
    0.        ]]
[0 0 0 ... 0 0 0]


In [23]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') 
imputer.fit(X)
X = imputer.transform(X)

In [24]:
print(X)

[[  1.          14.          15.         ...   1.           0.5
    0.        ]
 [  1.           3.           5.         ... 197.           7.63917986
  141.        ]
 [  1.           2.           2.         ...  76.           4.1085649
    8.        ]
 ...
 [  1.           1.           1.         ...  28.          14.20133129
    6.        ]
 [  1.           1.           1.         ...  27.          13.20133129
    5.        ]
 [  0.           0.           0.         ...   0.           0.
    0.        ]]


In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [26]:
print(X_train)

[[  1.           1.           1.         ...  41.          14.41233766
   24.        ]
 [  1.           6.          21.         ... 315.          27.95821091
  127.        ]
 [  1.           5.           5.         ...  15.           7.16666667
   12.        ]
 ...
 [  1.           2.           2.         ... 304.          12.45739627
  121.        ]
 [  1.           2.           2.         ...  19.           4.62200244
   12.        ]
 [  1.           4.           5.         ... 359.          21.03774378
  156.        ]]


In [27]:
print(y_train)

[0 0 1 ... 0 0 0]


In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [31]:
print(X_train)

[[-0.3132931  -0.53657716 -0.3003164  ... -0.72746394  0.08014339
  -0.55970861]
 [-0.3132931   0.27998239  0.732439   ...  1.27843464  1.39422553
   0.84541121]
 [-0.3132931   0.11667048 -0.09376532 ... -0.91780468 -0.62275753
  -0.72341189]
 ...
 [-0.3132931  -0.37326525 -0.24867863 ...  1.19790587 -0.10950503
   0.76355957]
 [-0.3132931  -0.37326525 -0.24867863 ... -0.88852149 -0.86961484
  -0.72341189]
 [-0.3132931  -0.04664143 -0.09376532 ...  1.60054974  0.72287256
   1.24102747]]


In [32]:
print(X_test)

[[-0.3132931   0.60660621  0.37097461 ... -0.04662975  0.13529432
   0.80448539]
 [-0.3132931  -0.37326525 -0.24867863 ... -0.42731123 -0.26938579
  -0.15045041]
 [-0.3132931  -0.37326525 -0.19704086 ...  0.25352296 -0.10908186
   0.76355957]
 ...
 [-0.3132931  -0.20995334 -0.14540309 ... -0.39802804 -0.0571252
  -0.24594399]
 [-0.3132931  -0.20995334 -0.19704086 ...  0.20227737 -0.28340725
  -0.27322787]
 [-0.3132931   0.11667048 -0.09376532 ...  0.01925743  0.2421433
  -0.38236339]]


In [33]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [34]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 0]]


In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1797  121]
 [ 473  225]]


0.7729357798165137

In [36]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.94      0.86      1918
           1       0.65      0.32      0.43       698

    accuracy                           0.77      2616
   macro avg       0.72      0.63      0.64      2616
weighted avg       0.75      0.77      0.74      2616

